/**
 * evolver0_token.h - Token定义
 */

#ifndef EVOLVER0_TOKEN_H
#define EVOLVER0_TOKEN_H

// Token类型定义
typedef enum {
    TOKEN_EOF = 0,
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_CHAR_LITERAL,
    
    // 关键字
    TOKEN_INT, TOKEN_CHAR, TOKEN_VOID, TOKEN_RETURN, 
    TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_FOR, TOKEN_DO, 
    TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,
    TOKEN_STRUCT, TOKEN_UNION, TOKEN_ENUM, TOKEN_TYPEDEF,
    TOKEN_STATIC, TOKEN_EXTERN, TOKEN_CONST, TOKEN_VOLATILE,
    TOKEN_SIZEOF, TOKEN_GOTO,
    
    // 操作符
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_MULTIPLY, TOKEN_DIVIDE, TOKEN_MOD,
    TOKEN_ASSIGN, TOKEN_ADD_ASSIGN, TOKEN_SUB_ASSIGN, TOKEN_MUL_ASSIGN,
    TOKEN_DIV_ASSIGN, TOKEN_MOD_ASSIGN,
    TOKEN_EQUAL, TOKEN_NOT_EQUAL,
    TOKEN_LESS, TOKEN_GREATER, TOKEN_LESS_EQUAL, TOKEN_GREATER_EQUAL,
    TOKEN_LOGICAL_AND, TOKEN_LOGICAL_OR, TOKEN_LOGICAL_NOT,
    TOKEN_BIT_AND, TOKEN_BIT_OR, TOKEN_BIT_XOR, TOKEN_BIT_NOT,
    TOKEN_LEFT_SHIFT, TOKEN_RIGHT_SHIFT,
    TOKEN_INCREMENT, TOKEN_DECREMENT,
    TOKEN_ARROW, TOKEN_DOT,
    TOKEN_QUESTION, TOKEN_COLON,
    
    // 标点
    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE,
    TOKEN_LBRACKET, TOKEN_RBRACKET, TOKEN_SEMICOLON, TOKEN_COMMA,
    TOKEN_ELLIPSIS,
    
    // 预处理
    TOKEN_HASH, TOKEN_INCLUDE, TOKEN_DEFINE, TOKEN_IFDEF, TOKEN_IFNDEF,
    TOKEN_ENDIF, TOKEN_UNDEF, TOKEN_PRAGMA,
    
    // 特殊
    TOKEN_UNKNOWN
} TokenType;

// Token结构体
typedef struct {
    TokenType type;
    char *value;
    int line;
    int column;
    const char *filename;
} Token;

#endif // EVOLVER0_TOKEN_H 