/* Automatically generated by configure - do not modify */

#define TCC_VERSION "0.9.28rc"

#define CC_NAME CC_gcc
#define GCC_MAJOR 0
#define GCC_MINOR 0

#if !(TCC_TARGET_I386 || TCC_TARGET_X86_64 || TCC_TARGET_ARM || TCC_TARGET_ARM64 || TCC_TARGET_RISCV64 || TCC_TARGET_C67)
#define TCC_TARGET_X86_64 1
#endif

#ifndef CONFIG_TCCDIR
#define CONFIG_TCCDIR "/mnt/persist/workspace/external/tcc/dist_new/lib/tcc"
#endif
#define CONFIG_TCC_PREDEFS 1
